### ISSUE TITLE
run task issue

### ISSUE THREAD

**Issue by josedurand** [cognitom/symbols-for-sketch#28]
Hello,

I have encounter an issue when i try to run symbols task

i runned npm install and installed xcode, global gulp and sketch tools  

Do you have an idea ?

I also noticed that there are many packages are deprecated

thx for your help

> gulp.task('symbols', () =>
>                                  ^
> SyntaxError: Unexpected token )
>     at Module._compile (module.js:439:25)
>     at Object.Module._extensions..js (module.js:474:10)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:364:17)
>     at require (module.js:380:17)
>     at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
>     at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:193:16)
>     at module.exports (/usr/local/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)
>     at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:185:9)
>

**Comment by josedurand** [comment]
It seems to be ES6

By using babel, I fix it. but now I have an issue with gulp-sketch. I opened an issue on the repo  

thx

**Comment by cognitom** [comment]
@josedurand hi! Thanks for reporting.
Why not use the newer version of node?
For the task runner, we have no reason to stick to 0.10.*, I think.

**Comment by cognitom** [comment]
For the users who encounters the same problem, here's a quick tip for upgrading node to v4 or later:

- install [n](https://github.com/tj/n) if you don't have `$ npm install -g n`
- install stable version of node `$ n stable`

Then we can use ES6 syntax freely ;-)

(I like `n` as a version management because of its simplicity, but there're [some](https://github.com/creationix/nvm) [other](https://github.com/hokaccha/nodebrew) [options](https://github.com/ekalinin/nodeenv), too. Use what you like)
